locale: en
enable_on_start: true

autostart:
  enabled: true
  count: 4

match:
  time: 1200
  weather: CLEAR
  maxpoints: 10
  maxhealth: 20
  duration: 1200

map:
  lobby:
    world: the-towers
    x: 0.611
    y: 207.0
    z: 1014.621
    yaw: 0.0
    pitch: 0.0
  spawns:
    iron: []
    coal: []
    emerald: []
    xp: []

teams:
  Red:
    color: RED
    spawn:
      world: the-towers
      x: 84.388
      y: 192.0
      z: 1152.477
      yaw: 0.0
      pitch: 0.0
    cage:
      world: the-towers
      x: 87.302
      y: 200.5
      z: 1152.512
      yaw: 0.0
      pitch: 0.0
  Blue:
    color: BLUE
    spawn:
      world: the-towers
      x: -83.420
      y: 192.0
      z: 1152.548
      yaw: 0.0
      pitch: 0.0
    cage:
      world: the-towers
      x: -83.501
      y: 200.5
      z: 1152.500
      yaw: 0.0
      pitch: 0.0